/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mbanking;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author wahyu
 */
public class beranda extends javax.swing.JFrame {
    private DefaultTableModel tabmode; 
    Connection con;
    Statement stat;
    ResultSet rs;
    String sql;
    query aa = new query();
    
    /**
     * Creates new form beranda
     */
    public beranda() throws SQLException{
        initComponents();
        Tampil_Jam();
        check();
        history();
        clear();
        namaRekening();
    }
    
    public void namaRekening() throws SQLException{
            rs = aa.ambilData();
            rs.next();
        
            txtNamaTarik.setText(rs.getString("nama"));
            txtRekTarek.setText(rs.getString("no_rek"));
            txtNamaTarik.setEnabled(false);   txtRekTarek.setEnabled(false);

            txtNamaSetor.setText(rs.getString("nama"));
            txtRekSetor.setText(rs.getString("no_rek"));
            txtNamaSetor.setEnabled(false);   txtRekSetor.setEnabled(false);

            txtRekTransfer.setText(rs.getString("nama"));
            txtRekTransfer.setEnabled(false);
    }
    
    public void history(){
        Object [] baris = {"Tanggal","Waktu","Jenis Transaksi","Debit","Kredit","Saldo","Keterangan"};
        tabmode = new DefaultTableModel(null, baris);
        tbl_history.setModel(tabmode);
        
        try {
                rs = aa.ambilDataTransaksi(); 
                while (rs.next()){
                    aa.setTgl(rs.getString("tanggal"));
                    aa.setWaktu(rs.getString("waktu"));
                    aa.setJk(rs.getString("jenis_transaksi"));
                    aa.setDebit(rs.getString("debit"));
                    aa.setKredit(rs.getString("kredit"));
                    aa.setSaldoT(rs.getString("saldo"));
                    aa.setKet(rs.getString("ket"));
                    
                    String[] data = {aa.getTgl(),aa.getWaktu(),aa.getJk(),aa.getDebit(),aa.getKredit(),aa.getSaldoT(),aa.getKet()};
                    tabmode.addRow(data);
                }
        } catch (Exception e) {
                System.out.print("Gagal Memuat Daftar Transaksi!"+"\n"+e);
        }
    }
    public void check () throws SQLException{
        rs = aa.ambilData();
        rs.next();
        lbl_great.setText("Selamat Datang, "+rs.getString("nama")+"!");
        lbl_noRek.setText(rs.getString("no_rek"));
        lbl_saldo.setText(rs.getString("saldo"));
    }
    
    public void Tampil_Jam(){
        ActionListener taskPerformer = new ActionListener() {
 
        @Override
            public void actionPerformed(ActionEvent evt) {
            String nol_jam = "", nol_menit = "",nol_detik = "";
 
            java.util.Date dateTime = new java.util.Date();
            int nilai_jam = dateTime.getHours();
            int nilai_menit = dateTime.getMinutes();
            int nilai_detik = dateTime.getSeconds();
            
            java.util.Date tglsekarang = new java.util.Date();
            SimpleDateFormat smpdtfmt = new SimpleDateFormat("dd-MM-yyyy", Locale.getDefault());
            String tanggal = smpdtfmt.format(tglsekarang);
 
            if(nilai_jam <= 9) nol_jam= "0";
            if(nilai_menit <= 9) nol_menit= "0";
            if(nilai_detik <= 9) nol_detik= "0";
 
            String jam = nol_jam + Integer.toString(nilai_jam);
            String menit = nol_menit + Integer.toString(nilai_menit);
            String detik = nol_detik + Integer.toString(nilai_detik);
 
            lbl_date.setText(tanggal);
            lbl_time.setText(jam + ":" + menit+ ":" + detik);
            }
        };
        new Timer(1000, taskPerformer).start();
    }
    
    public void clear(){
        txtNominlSetor.setText("");
        txtNominlTarek.setText("");
        txtNominlTransaksi.setText("");
        txtNamaTransfer.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_date = new javax.swing.JLabel();
        lbl_time = new javax.swing.JLabel();
        tabPane = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        lbl_great = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_noRek = new javax.swing.JLabel();
        lbl_saldo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbl_great1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_history = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        lbl_great2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNamaTarik = new javax.swing.JTextField();
        txtRekTarek = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNominlTarek = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnTarek = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnSetor = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtNominlSetor = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        lbl_great3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtNamaSetor = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtRekSetor = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        btn_transaksi = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txtNominlTransaksi = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        lbl_great4 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtNamaTransfer = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtRekTransfer = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        lbl_namaTrans = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home | Mobile Banking System");

        jPanel1.setBackground(new java.awt.Color(59, 99, 194));

        jLabel1.setFont(new java.awt.Font("Montserrat ExtraBold", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bank Universitas Riau");

        jLabel2.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mudah, Aman dan Terpercaya");

        jLabel3.setFont(new java.awt.Font("Montserrat Medium", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mbanking/img/logOut.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        lbl_date.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        lbl_date.setForeground(new java.awt.Color(255, 255, 255));
        lbl_date.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_date.setText("time");

        lbl_time.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        lbl_time.setForeground(new java.awt.Color(255, 255, 255));
        lbl_time.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_time.setText("time");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_date)
                    .addComponent(lbl_time))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lbl_date))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lbl_time))))
                .addGap(28, 28, 28))
        );

        tabPane.setBackground(new java.awt.Color(255, 255, 255));
        tabPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N

        lbl_great.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 24)); // NOI18N
        lbl_great.setText("Selamat Datang, ...!");

        jLabel4.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        jLabel4.setText("Nomor Rekening :");

        lbl_noRek.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        lbl_noRek.setText("Nomor Rekening");

        lbl_saldo.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        lbl_saldo.setText("Rp. 0.000");

        jLabel5.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        jLabel5.setText("Saldo :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(42, 42, 42)
                        .addComponent(lbl_saldo))
                    .addComponent(lbl_great)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(42, 42, 42)
                        .addComponent(lbl_noRek)))
                .addContainerGap(411, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(lbl_great)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lbl_noRek))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lbl_saldo))
                .addContainerGap(297, Short.MAX_VALUE))
        );

        tabPane.addTab("Home", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        lbl_great1.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 24)); // NOI18N
        lbl_great1.setText("History Transaksi");

        tbl_history.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        tbl_history.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_history);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_great1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lbl_great1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabPane.addTab("History", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        lbl_great2.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 24)); // NOI18N
        lbl_great2.setText("Tarik Tunai");

        jLabel6.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        jLabel6.setText("Nama");

        txtNamaTarik.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        txtNamaTarik.setText("jTextField1");

        txtRekTarek.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        txtRekTarek.setText("jTextField1");

        jLabel7.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        jLabel7.setText("Nomor Rekening");

        txtNominlTarek.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        txtNominlTarek.setText("jTextField1");

        jLabel8.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        jLabel8.setText("Nominal");

        jLabel9.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Minimal Tarik Tunai IDR 50.000");

        btnTarek.setBackground(new java.awt.Color(59, 99, 194));
        btnTarek.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        btnTarek.setForeground(new java.awt.Color(255, 255, 255));
        btnTarek.setText("Lanjut");
        btnTarek.setBorder(null);
        btnTarek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTarekActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(lbl_great2)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtNamaTarik, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRekTarek, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(142, 142, 142)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel9)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(txtNominlTarek, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnTarek, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(109, 109, 109))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lbl_great2)
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNamaTarik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNominlTarek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)))
                .addGap(9, 9, 9)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRekTarek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTarek, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(192, Short.MAX_VALUE))
        );

        tabPane.addTab("Tarik", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        btnSetor.setBackground(new java.awt.Color(59, 99, 194));
        btnSetor.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        btnSetor.setForeground(new java.awt.Color(255, 255, 255));
        btnSetor.setText("Lanjut");
        btnSetor.setBorder(null);
        btnSetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetorActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Minimal Tarik Tunai IDR 50.000");

        txtNominlSetor.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        txtNominlSetor.setText("jTextField1");

        jLabel11.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        jLabel11.setText("Nominal");

        lbl_great3.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 24)); // NOI18N
        lbl_great3.setText("Setor Tunai");

        jLabel12.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        jLabel12.setText("Nama");

        txtNamaSetor.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        txtNamaSetor.setText("jTextField1");

        jLabel13.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        jLabel13.setText("Nomor Rekening");

        txtRekSetor.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        txtRekSetor.setText("jTextField1");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(lbl_great3)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(txtNamaSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRekSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(142, 142, 142)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel10)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(txtNominlSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnSetor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(109, 109, 109))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lbl_great3)
                .addGap(32, 32, 32)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNamaSetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNominlSetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)))
                .addGap(9, 9, 9)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRekSetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(192, Short.MAX_VALUE))
        );

        tabPane.addTab("Setor", jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        btn_transaksi.setBackground(new java.awt.Color(59, 99, 194));
        btn_transaksi.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        btn_transaksi.setForeground(new java.awt.Color(255, 255, 255));
        btn_transaksi.setText("Lanjut");
        btn_transaksi.setBorder(null);
        btn_transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_transaksiActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Minimal Tarik Tunai IDR 50.000");

        txtNominlTransaksi.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        txtNominlTransaksi.setText("jTextField1");

        jLabel15.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        jLabel15.setText("Nominal");

        lbl_great4.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 24)); // NOI18N
        lbl_great4.setText("Transfer");

        jLabel16.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        jLabel16.setText("Dari Rekening");

        txtNamaTransfer.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        txtNamaTransfer.setText("jTextField1");
        txtNamaTransfer.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtNamaTransferInputMethodTextChanged(evt);
            }
        });
        txtNamaTransfer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNamaTransferKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNamaTransferKeyTyped(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        jLabel17.setText("Nomor Rekening Tujuan");

        txtRekTransfer.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        txtRekTransfer.setText("jTextField1");

        jLabel18.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        jLabel18.setText("Nama Penerima");

        lbl_namaTrans.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        lbl_namaTrans.setText("Nama TIdak Ditemukan..");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(lbl_great4)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(txtNamaTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRekTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(142, 142, 142)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel14)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(txtNominlTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btn_transaksi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lbl_namaTrans)
                    .addComponent(jLabel18))
                .addGap(109, 109, 109))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lbl_great4)
                .addGap(32, 32, 32)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtRekTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNominlTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)))
                .addGap(9, 9, 9)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNamaTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_namaTrans)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        tabPane.addTab("Transfer", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 939, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tabPane))
        );

        setSize(new java.awt.Dimension(953, 577));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTarekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTarekActionPerformed
        // TODO add your handling code here:
        if (txtNominlTarek.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Masukkan Nominal Penarikan");
        } else {
            aa.setTgl(lbl_date.getText());
            aa.setWaktu(lbl_time.getText());
            aa.setJk("Tarik Tunai");
            aa.setDebit("0");
            aa.setKredit(txtNominlTarek.getText());
            aa.setKet("-");
            rs = aa.ambilData();

            try {
                rs.next();
                System.out.println(aa.getSaldoTarik(rs.getString("saldo")));
                    if(Integer.parseInt(txtNominlTarek.getText()) >= 50000 ){
                        System.err.println(rs.getString("saldo"));
                        if (Integer.parseInt(rs.getString("saldo"))>=Integer.parseInt(txtNominlTarek.getText())){
                            if(Integer.parseInt(JOptionPane.showInputDialog("Masukkan Pin Anda")) == Integer.parseInt(rs.getString("pin"))){
                            System.err.println(rs.getString("pin"));
                            aa.Transaksi();
                            System.err.println("SUKSeS!!"); 
                            JOptionPane.showMessageDialog(null, "Tarik Tunai Berhasil", "Succesfull", JOptionPane.INFORMATION_MESSAGE);
                            tabPane.setSelectedIndex(1);
                            aa.ubahSaldo();
                            check();
                            history();
                            clear();
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "Saldo Anda tidak mencukupi untuk melakukan Penarikan Tunai!");
                        } 
                    } else {
                        JOptionPane.showMessageDialog(null, "Minimal Penarekan Rp. 50.000,-");
                    }

            } catch (SQLException ex) {
                System.out.println(ex); 
            }
        }
    }//GEN-LAST:event_btnTarekActionPerformed

    private void btnSetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetorActionPerformed
        // TODO add your handling code here:
        if (txtNominlSetor.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Masukkan Nominal Penyetoran");
        } else {
            aa.setTgl(lbl_date.getText());
            aa.setWaktu(lbl_time.getText());
            aa.setJk("Setor Tunai");
            aa.setKredit("0");
            aa.setDebit(txtNominlSetor.getText());
            aa.setKet("-");
            rs = aa.ambilData();

            try {
                rs.next();
                System.out.println(aa.getSaldoSetor(Integer.parseInt(rs.getString("saldo"))));
                    System.err.println(rs.getString("saldo"));
                    if(Integer.parseInt(txtNominlSetor.getText()) >= 50000 ){
                        if(Integer.parseInt(JOptionPane.showInputDialog("Masukkan Pin Anda")) == Integer.parseInt(rs.getString("pin"))){
                            System.err.println(rs.getString("pin"));
                            aa.Transaksi();
                            System.err.println("SUKSeS!!");
                            JOptionPane.showMessageDialog(null, "Setor Tunai Berhasil", "Succesfull", JOptionPane.INFORMATION_MESSAGE);
                            tabPane.setSelectedIndex(1);
                            aa.ubahSaldo();
                            check();
                            history();
                            clear();
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Minimal Penyetoran Rp. 50.000,-");
                    }
            } catch (SQLException ex) {
                System.out.println(ex); 
            }
        }
    }//GEN-LAST:event_btnSetorActionPerformed

    private void btn_transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_transaksiActionPerformed
        // TODO add your handling code here:
        if (txtNamaTransfer.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Masukkan Nomor Rekening Penerima");
        } else if (txtNominlTransaksi.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Masukkan Nominal Transfer");
        } else {
            aa.setTgl(lbl_date.getText());
            aa.setWaktu(lbl_time.getText());
            aa.setJk("Transfer");
            aa.setDebit("0");
            aa.setKredit(txtNominlTransaksi.getText());
            aa.setKet(aa.getNamaPenerima());
            rs = aa.ambilData();

            try {
                rs.next();
                System.out.println(aa.getSaldoTarik(rs.getString("saldo")));
                if(Integer.parseInt(txtNominlTransaksi.getText()) >= 50000 ){
                    if(Integer.parseInt(rs.getString("saldo")) >= Integer.parseInt(txtNominlTransaksi.getText())){
                        System.err.println(rs.getString("saldo"));
                        if(Integer.parseInt(JOptionPane.showInputDialog("Masukkan Pin Anda")) == Integer.parseInt(rs.getString("pin"))){
                            System.err.println(rs.getString("pin"));
                            aa.Transaksi();
                            JOptionPane.showMessageDialog(null, "Setor Tunai Berhasil", "Succesfull", JOptionPane.INFORMATION_MESSAGE);
                            tabPane.setSelectedIndex(1);
                            aa.ubahSaldo();
                            aa.ubahSaldoPen();
                            check();
                            history();
                            clear();
                        } 
                    } else {
                        JOptionPane.showMessageDialog(null,  "Maaf Saldo Anda tidak Mencukupi untuk melakukan Transfer", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Minimal Transfer Rp. 50.000,-");
                }
            } catch (SQLException ex) {
                System.out.println(ex); 
            }
        }
    }//GEN-LAST:event_btn_transaksiActionPerformed

    private void txtNamaTransferKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaTransferKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtNamaTransferKeyTyped

    private void txtNamaTransferInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtNamaTransferInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaTransferInputMethodTextChanged

    private void txtNamaTransferKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaTransferKeyReleased
        // TODO add your handling code here:
        rs = aa.rekPenerima(txtNamaTransfer.getText());
        try {
            rs.next();
            if (txtNamaTransfer.getText().equals(rs.getString("no_rek"))){
                aa.setNamaPenerima(rs.getString("nama"));
                lbl_namaTrans.setText(aa.getNamaPenerima());
                aa.setSaldoPenerima(Integer.parseInt(rs.getString("saldo")));
                System.out.println(aa.getSaldoPenerima());
                aa.setRelPenerima(rs.getString("no_rek"));
            } else {
                lbl_namaTrans.setText("Nama Nasabah Tidak Ditemukan");
            }
        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_txtNamaTransferKeyReleased

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        try {
            // TODO add your handling code here:
            new login().setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(beranda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new beranda().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(beranda.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSetor;
    private javax.swing.JButton btnTarek;
    private javax.swing.JButton btn_transaksi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_date;
    private javax.swing.JLabel lbl_great;
    private javax.swing.JLabel lbl_great1;
    private javax.swing.JLabel lbl_great2;
    private javax.swing.JLabel lbl_great3;
    private javax.swing.JLabel lbl_great4;
    private javax.swing.JLabel lbl_namaTrans;
    private javax.swing.JLabel lbl_noRek;
    private javax.swing.JLabel lbl_saldo;
    private javax.swing.JLabel lbl_time;
    private javax.swing.JTabbedPane tabPane;
    private javax.swing.JTable tbl_history;
    private javax.swing.JTextField txtNamaSetor;
    private javax.swing.JTextField txtNamaTarik;
    private javax.swing.JTextField txtNamaTransfer;
    private javax.swing.JTextField txtNominlSetor;
    private javax.swing.JTextField txtNominlTarek;
    private javax.swing.JTextField txtNominlTransaksi;
    private javax.swing.JTextField txtRekSetor;
    private javax.swing.JTextField txtRekTarek;
    private javax.swing.JTextField txtRekTransfer;
    // End of variables declaration//GEN-END:variables
}
